version: '3.8'

services:
  virtual-facility:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=virtual-facility
    command: npm run start:dev -- virtual-facility
    ports:
      - '3000:3000'
    environment:
      - POSTGRES_HOST=virtual-facility-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=virtual-facility
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - NATS_URL=nats://nats:4222
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/virtual-facility:/usr/src/app/apps/virtual-facility
    depends_on:
      - virtual-facility-db
      - workflows-service
      - rabbitmq
      - nats
  virtual-facility-db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=virtual-facility
    volumes:
      - virtual-facility-db-data:/var/lib/postgresql/data

  workflows-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=workflows-service
    command: npm run start:dev -- workflows-service
    environment:
      - POSTGRES_HOST=workflows-service-db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=workflows-service
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - NATS_URL=nats://nats:4222
    deploy:
      replicas: 3
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/workflows-service:/usr/src/app/apps/workflows-service
    depends_on:
      - workflows-service-db
      - rabbitmq
      - nats
  workflows-service-db:
    image: postgres:13.2-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=workflows-service
    volumes:
      - workflows-service-db-data:/var/lib/postgresql/data

  alarms-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=alarms-service
    command: npm run start:dev -- alarms-service
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/alarms-service:/usr/src/app/apps/alarms-service
    depends_on:
      - nats
      - alarms-generator
  alarms-generator:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=alarms-generator
    command: npm run start:dev -- alarms-generator
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/alarms-generator:/usr/src/app/apps/alarms-generator
    depends_on:
      - nats

  alarms-classifier-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=alarms-classifier-service
    command: npm run start:dev -- alarms-classifier-service
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/alarms-classifier-service:/usr/src/app/apps/alarms-classifier-service
    depends_on:
      - nats
  notifications-service:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - APP_NAME=notifications-service
    command: npm run start:dev -- notifications-service
    environment:
      - NATS_URL=nats://nats:4222
    volumes:
      - ./libs:/usr/src/app/libs
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./apps/notifications-service:/usr/src/app/apps/notifications-service
    depends_on:
      - nats

  nats:
    image: nats:2.2.2-alpine

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  virtual-facility-db-data:
  workflows-service-db-data:
